# Generated by Django 5.0.3 on 2024-03-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name Institution'),
        ),
        migrations.AlterField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.institution'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name Program'),
        ),
        migrations.CreateModel(
            name='AccStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accrediting_Body', models.CharField(max_length=50)),
                ('Accreditation_Status', models.CharField(max_length=50)),
                ('Accreditation_Start_Date', models.DateField()),
                ('Accreditation_End_Date', models.DateField()),
                ('Compliance_Level', models.CharField(max_length=50)),
                ('Accreditation_Criteria', models.CharField(max_length=50)),
                ('Progress_Towards_Accreditation', models.FileField(upload_to='Progress/Towards/Accreditation')),
                ('Self_Assessment_Reports', models.FileField(upload_to='Self-Assessment/Reports')),
                ('Site_Visit_Reports', models.FileField(upload_to='Site/Visit/Reports')),
                ('Supporting_Documentation', models.FileField(upload_to='Supporting/Documentation')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.program', verbose_name='اسم القسم')),
            ],
        ),
    ]
