# Generated by Django 5.0.3 on 2024-03-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_institution_name_alter_program_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accstatus',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.institution'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.program'),
        ),
    ]
