# Generated by Django 5.0.3 on 2024-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_accstatus_institution_alter_accstatus_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Criteria',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Compliance_Level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
    ]
