# Generated by Django 5.0.3 on 2024-04-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_accstatus_accreditation_criteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accstatus',
            name='Progress_Towards_Accreditation',
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Criteria',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='معايير الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_End_Date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Start_Date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Status',
            field=models.CharField(blank=True, choices=[('معتمد', 'معتمد'), ('غير معتمد', 'غير معتمد'), ('قيد الاعتماد', 'قيد الاعتماد')], max_length=50, null=True, verbose_name='حالة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Accrediting_Body',
            field=models.CharField(blank=True, choices=[('المركز الوطني', 'المركز الوطني')], max_length=50, null=True, verbose_name='هيئة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Compliance_Level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True, verbose_name='مستوى الامتثال'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Self_Assessment_Reports',
            field=models.FileField(blank=True, null=True, upload_to='Self-Assessment/Reports', verbose_name='تقرير التقييم الذاتي'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Site_Visit_Reports',
            field=models.FileField(blank=True, null=True, upload_to='Site/Visit/Reports', verbose_name='تقرير زيادة الموقع'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='Supporting_Documentation',
            field=models.FileField(blank=True, null=True, upload_to='Supporting/Documentation', verbose_name='التوثيق الداعم'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.institution', verbose_name='اسم المؤسسة'),
        ),
        migrations.AlterField(
            model_name='accstatus',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.program', verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='project.institution'),
        ),
    ]
