# Generated by Django 5.0.3 on 2024-05-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuont', '0002_depatment'),
        ('project', '0005_remove_accstatus_progress_towards_accreditation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccStatusMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accrediting_Body', models.CharField(blank=True, choices=[('المركز الوطني', 'المركز الوطني')], max_length=50, null=True, verbose_name='هيئة الاعتماد')),
                ('Accreditation_Status', models.CharField(blank=True, choices=[('معتمد', 'معتمد'), ('غير معتمد', 'غير معتمد'), ('قيد الاعتماد', 'قيد الاعتماد')], max_length=50, null=True, verbose_name='حالة الاعتماد')),
                ('Accreditation_Start_Date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الاعتماد')),
                ('Accreditation_End_Date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الاعتماد')),
                ('Compliance_Level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True, verbose_name='مستوى الامتثال')),
                ('Accreditation_Criteria', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='معايير الاعتماد')),
                ('Self_Assessment_Reports', models.FileField(blank=True, null=True, upload_to='Self-Assessment/Reports', verbose_name='تقرير التقييم الذاتي')),
                ('Site_Visit_Reports', models.FileField(blank=True, null=True, upload_to='Site/Visit/Reports', verbose_name='تقرير زيادة الموقع')),
                ('Supporting_Documentation', models.FileField(blank=True, null=True, upload_to='Supporting/Documentation', verbose_name='التوثيق الداعم')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accuont.depatment', verbose_name='اسم القسم')),
            ],
        ),
    ]
