# Generated by Django 5.0.3 on 2024-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_accstatusmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='accstatusmain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
