# Generated by Django 5.0.3 on 2024-05-03 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_accstatusmain_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accstatusmain',
            name='department',
        ),
        migrations.AddField(
            model_name='accstatusmain',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم القسم'),
            preserve_default=False,
        ),
    ]
