# Generated by Django 5.0.3 on 2024-05-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_accstatusmain_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المعيار')),
                ('descripe', models.CharField(blank=True, max_length=250, null=True, verbose_name='وصف المعيار')),
            ],
        ),
    ]
