# Generated by Django 5.0.3 on 2024-05-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_accstatus_accrediting_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstatusmain',
            name='Accrediting_Body',
            field=models.CharField(blank=True, choices=[('محلي', 'محلي'), ('دولي', 'دولي')], max_length=50, null=True, verbose_name='نوع التقديم'),
        ),
    ]
