# Generated by Django 5.0.3 on 2024-05-24 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_accstatusmain_accrediting_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Accreditation_Criteria',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Accreditation_End_Date',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Accreditation_Start_Date',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Compliance_Level',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Self_Assessment_Reports',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Site_Visit_Reports',
        ),
        migrations.RemoveField(
            model_name='accstatusmain',
            name='Supporting_Documentation',
        ),
        migrations.CreateModel(
            name='StandardAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField(default=0)),
                ('acc_status_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.accstatusmain')),
                ('quality_standards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.quality_standards')),
            ],
        ),
    ]
