# Generated by Django 5.0.3 on 2024-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_college_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_activities',
            name='type_activity',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
