# Generated by Django 5.0.3 on 2024-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_college_activities_type_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Status',
            field=models.CharField(blank=True, choices=[('معتمد', 'معتمد'), ('غير معتمد', 'غير معتمد'), ('متقدمة الاعتماد', 'متقدمة الاعتماد'), ('قيد الاعتماد', 'قيد الاعتماد')], max_length=50, null=True, verbose_name='حالة الاعتماد'),
        ),
    ]
