# Generated by Django 5.0.3 on 2024-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_accstatus_accreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstatus',
            name='Accreditation_Status',
            field=models.CharField(blank=True, choices=[('معتمد', 'معتمد'), ('غير معتمد', 'غير معتمد'), ('متقدمة للاعتماد', 'متقدمة للاعتماد'), ('غير متقدمة للاعتماد', 'غير متقدمة للاعتماد')], max_length=50, null=True, verbose_name='حالة الاعتماد'),
        ),
    ]
