# Generated by Django 5.0.3 on 2024-05-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_accstatus_accreditation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accstatusmain',
            name='Accreditation_Status',
            field=models.CharField(blank=True, choices=[('معتمد', 'معتمد'), ('غير معتمد', 'غير معتمد'), ('متقدمة للاعتماد', 'متقدمة للاعتماد'), ('غير متقدمة للاعتماد', 'غير متقدمة للاعتماد')], max_length=50, null=True, verbose_name='حالة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='accstatusmain',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_main', to=settings.AUTH_USER_MODEL, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='college_activities',
            name='acc_status_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_active', to='project.accstatusmain'),
        ),
    ]
