# Generated by Django 5.0.3 on 2024-06-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_standardacc_acc_status_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='accstatusmain',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
